### ISSUE TITLE
Issue with PASSPHRASE containing special characters

### ISSUE THREAD

**Issue by ghost** [hashicorp/ghaction-import-gpg#6]
The `env.PASSPHRASE` should be modified as to not escape special characters?

https://github.com/hashicorp/ghaction-import-gpg/blob/78437f97569a473e42b227be84d4084c2dfb49ba/action.yml#L16

The workaround would be to manually escape such characters in the environment variable, but that is less than ideal.

**Comment by bapung** [comment]
Had the same issue with passphrase containing "$" character. Escaping the "$" in env variable resolves the problem but it is indeed less than ideal.

passphrase: thisis$upers3cret

Adding the PASSPHRASE to repository secret
NOT working: thisis$upers3cret
working: thisis\$upers3cret.

**Comment by mdeggies** [comment]
Hey everyone- This action has been deprecated per https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410 and the repo will be archived soon. We recommend using the [crazy-max upstream](https://github.com/crazy-max/ghaction-import-gpg) directly.
