### ISSUE TITLE
Re: "Note [5/6/2021]" - now fixed upstream

### ISSUE THREAD

**Issue by OJFord** [hashicorp/ghaction-import-gpg#7]
This issue is fixed in the latest release:
https://github.com/crazy-max/ghaction-import-gpg/releases/tag/v4.1.0

(I have no idea if it's related, but perhaps worth mentioning I now hit goreleaser/goreleaser-action#201 /  hashicorp/terraform-website#1549 - 'signing failed, inappropriate ioctl for device'.)

**Comment by mdeggies** [comment]
Thanks for the note! This action has been deprecated per https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410 and the repo will be archived soon. We recommend using the [crazy-max upstream](https://github.com/crazy-max/ghaction-import-gpg) directly.
