### ISSUE TITLE
actionlint complaining

### ISSUE THREAD

**Issue by remyleone** [hashicorp/ghaction-import-gpg#9]
### Expected Behavior

When I run actionlint I expect that no errors occur.

### Actual Behavior

Errors occurred:

```
$ actionlint
.github/workflows/ci.yml:51:159: property "name" is not defined in object type {email: string; fingerprint: string; keyid: string} [expression]
.github/workflows/ci.yml:92:159: property "name" is not defined in object type {keyid: string; email: string; fingerprint: string} [expression]
.github/workflows/pre-checkin.yml:30:9: shellcheck reported issue in this script: SC2006:style:1:7: Use $(...) notation instead of legacy backticks `...` [shellcheck]
   |
30 |         run: |
   |         ^~~~
```

### Steps to Reproduce

run actionlint

### Important Factoids

```
$ actionlint --version
1.6.12
installed by building from source
built with go1.18.1 compiler for darwin/amd64
```

**Comment by mdeggies** [comment]
Thanks for the note! This action has been deprecated per https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410 and the repo will be archived soon. We recommend using the [crazy-max upstream](https://github.com/crazy-max/ghaction-import-gpg) directly.
